### ISSUE TITLE
Requesting project name change

### ISSUE THREAD

**Issue by wizonesolutions** [desertbit/fillpdf#1]
I wanted to contact you privately, but your site doesn't have any such info, so I'm opening an issue.

I'm the maintainer for the Drupal FillPDF module at https://drupal.org/project/fillpdf, and it has similar functionality to this library. I also incorporate it in my FillPDF Service product.

For trademark/lack of confusion reasons, could you choose another name? Thanks.

**Comment by r0l1** [comment]
Thank you for pointing this out. However I don't see a problem with the naming. This is an open source golang library and it has nothing to do with Drupal and PHP development?! Same thing with: [fill-pdf](https://www.npmjs.com/package/fill-pdf) from NPM. If you don't agree, please explain your problem in detail.
Thanks :)

**Comment by wizonesolutions** [comment]
Well, that's fair enough. If someone actually does ask me for support on
one of those, I'll take it up then. I'll trust that developers won't
experience confusing similarity (
https://en.wikipedia.org/wiki/Confusing_similarity) :)

At this point, it's still theoretical, so I don't really mind, but figured
I should be responsible and say something.
