### ISSUE TITLE
pdftk utility is not installed — installing pdftk doesn't solve the error

### ISSUE THREAD

**Issue by maxiride** [desertbit/fillpdf#5]
Hi, I've tried to use this package but i get the error: `pdftk utility is not installed!`, i then proceeded to [installed pdftk](https://pdftk.en.softonic.com/), and I've added the executable to the PATH, however, the error is still thrown when attempting to fill a pdf.

Any guideline on how to proceed?

go version go1.16.2 windows/amd64
Windows 10

**Comment by maxiride** [comment]
After searching a while I found [another library](https://github.com/kazekim/pdfinject-go), inspired by this one where they specifically report that pdftk server version is need and it is retrievable [here](https://www.pdflabs.com/tools/pdftk-server/).

I'd suggest to include this precious information in the readme.

**Comment by r0l1** [comment]
Thanks for the info. Windows is not a target for me. Please feel free to provide a pull request with the Windows documentation.

**Comment by r0l1** [comment]
Thanks for the fast pull request!
